# Introduction to Numpy

In [2]:
import numpy as np
np

<module 'numpy' from '/opt/miniconda3/envs/ml-zoomcamp/lib/python3.11/site-packages/numpy/__init__.py'>

## Creating Arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(7, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [8]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [10]:
a[3] == 4

np.True_

In [11]:
a[3] = 10
a

array([ 1,  2,  3, 10,  5])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Multi-dimensional arrays

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
n = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10], 
    [11, 12, 13, 14, 1]
])

In [26]:
n[0, 3] = 20
n

array([[ 1,  2,  3, 20,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14,  1]])

In [ ]:
n[1]

array([ 6,  7,  8,  9, 10])

In [33]:
n[:, 2]

array([ 3,  8, 13])

## Randomly Generated Arrays


In [37]:
np.random.seed(2)  # For reproducibility
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [38]:
np.random.randn(5, 2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [40]:
np.random.randint(low=0, high=10, size=(3, 4))

array([[3, 9, 2, 0],
       [4, 2, 4, 1],
       [7, 8, 2, 9]])

# Element-wise operations

In [42]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [43]:
a + 1 

array([2, 3, 4, 5, 6])

In [ ]:
a * 2

array([ 2,  4,  6,  8, 10])

In [47]:
b = (10 + (a*2)) / 5
b

array([2.4, 2.8, 3.2, 3.6, 4. ])

In [48]:
a + b

array([3.4, 4.8, 6.2, 7.6, 9. ])

# Comparison Operations

In [52]:
a >= 3

array([False, False,  True,  True,  True])

In [54]:
a < b

array([ True,  True,  True, False, False])

In [56]:
a[a >= 3]

array([3, 4, 5])

In [57]:
b[a < b]

array([2.4, 2.8, 3.2])

## Summarizing Operations

In [58]:
a.min()

np.int64(1)

In [59]:
a.max()

np.int64(5)

In [60]:
a.sum()

np.int64(15)

In [61]:
a.mean()

np.float64(3.0)

In [62]:
a.std()

np.float64(1.4142135623730951)

In [63]:
n.sum()

np.int64(122)