# Linear Algebra

In [ ]:
import numpy as np

## Vector Operations

In [5]:
u = np.array([2, 4, 6, 8])
v = np.array([1, 3, 5, 7])

print(u, v)

[2 4 6 8] [1 3 5 7]


In [8]:
# Addition
print("Addition:", u + v)

# Subtraction
print("Subtraction:", u - v)

# Scalar Multiplication
print("Scalar Multiplication:", 2 * u)

# Scalar Division
print("Scalar Division:", u / 2)

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Scalar Multiplication: [ 4  8 12 16]
Scalar Division: [1. 2. 3. 4.]


## Multiplication

In [13]:
# Vector Multiplication (Dot Product)
print("Dot Product:", np.dot(u, v))

print("Dot Product (alternative):", u.dot(v))

print("Dot Product (manual):", sum(u_i * v_i for u_i, v_i in zip(u, v)))

Dot Product: 100
Dot Product (alternative): 100
Dot Product (manual): 100


In [21]:
# Matrix Vector Multiplication
U = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("U Matrix:\n", U)
print("U shape:", U.shape)
print("v shape:", v.shape)

print("Matrix-Vector Multiplication:", U.dot(v))
print("Matrix-Vector Multiplication (alternative):", np.dot(U, v))
print("Matrix-Vector Multiplication (manual):", [sum(U_i * v_i for U_i, v_i in zip(U_row, v)) for U_row in U])
print("Multiplication shape:", U.dot(v).shape)

U Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
U shape: (3, 4)
v shape: (4,)
Matrix-Vector Multiplication: [ 50 114 178]
Matrix-Vector Multiplication (alternative): [ 50 114 178]
Matrix-Vector Multiplication (manual): [np.int64(50), np.int64(114), np.int64(178)]
Multiplication shape: (3,)


In [22]:
# Matrix matrix Multiplication
V = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

print("V Matrix:\n", V)
print("V shape:", V.shape)

print("Matrix-Matrix Multiplication:\n", U.dot(V))
print("Matrix-Matrix Multiplication (alternative):\n", np.dot(U, V))
print("Matrix-Matrix Multiplication (manual):\n", [[sum(U_i * V_ij for U_i, V_ij in zip(U_row, V_col)) for V_col in V.T] for U_row in U])
print("Multiplication shape:", U.dot(V).shape)

V Matrix:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
V shape: (4, 2)
Matrix-Matrix Multiplication:
 [[ 50  60]
 [114 140]
 [178 220]]
Matrix-Matrix Multiplication (alternative):
 [[ 50  60]
 [114 140]
 [178 220]]
Matrix-Matrix Multiplication (manual):
 [[np.int64(50), np.int64(60)], [np.int64(114), np.int64(140)], [np.int64(178), np.int64(220)]]
Multiplication shape: (3, 2)


## Identity Matrix

In [24]:
I = np.eye(3)  # Identity matrix of size 3x3

In [26]:
V = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

V.dot(I)  # Should return V unchanged

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Matrix Inverse

In [36]:
# Define a 2x2 matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:\n", matrix)
print("\nInverse Matrix:\n", inverse_matrix)

# Verify the inversion
identity_check = np.matmul(inverse_matrix, matrix)
print("\nIdentity Check (Matrix * Inverse):\n", identity_check)

Original Matrix:
 [[4 7]
 [2 6]]

Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Identity Check (Matrix * Inverse):
 [[ 1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00]]
